# -*- coding: utf-8 -*-
"""Factorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oHd8F6i6dK0gbUFPDD3JMqJuVcakJG6p
"""

def factorial(int):
  n = 1
  solution = 0
  while int >= n:
    # 5 + 4 + 3 + 2 + 1
    solution = solution + n
    n += 1
  return solution

number = 5
factorial(number)